### ISSUE TITLE
UAV flies off to the sky after some time

### ISSUE THREAD

**Issue by EceChaik** [larics/icuas22_competition#16]
Hi guys,

I am running into a repeated issue with the competition stack that I haven't been able to solve.
The UAV arms and takes off successfully, it also successfully listens to commands on the /red/tracker/input_pose topic.
However, after some time in the simulation, without fail it starts climbing infinitely. 
There doesn't appear to be a clear error that triggers this behavior, but I am attaching a screenshot of the main terminals when this occurs.
![Screenshot from 2022-02-23 17-12-48](https://user-images.githubusercontent.com/26469569/155328060-a8ee9dee-4064-4684-81da-5acb4d92e87e.png)
I think it has something to do with the 'height' messages appearing in the ardupilot console, though I have no idea where they originate.

**Comment by fpetric** [comment]
@EceChaik thanks for the report, we will look into it

**Comment by EceChaik** [comment]
Hi @lmark1 ,
I thought that in these simulations the uav is flown in GUIDED_NOGPS mode and you control the position with your own position controller, then feed the attitude commands to Ardupilot.
If that's the case, why should the internal altitude estimate matter, since you're hijacking the internal position controller?
Unless you are still using the ardupilot's internal positioning estimate

**Comment by lmark1** [comment]
Technically that is true. 

By default the Ardupilot firmware interprets the thrust command

**Comment by lmark1** [comment]
We do control the UAV with our own position controller. However... 

By default the Ardupilot firmware interprets the thrust command (in GUIDED_NOGPS mode) as climb rate. When using 'thrust' as climb rate Ardupilot still requires some altitude information in order to know if it's climbing up or down.

By changing the parameter [GUID_OPTIONS 8] (https://github.com/larics/icuas22_competition/blob/8c4d15b49b82a3bfb8c7561b76caeb5724d60da9/parameters/arducopter_nogps.params#L361) we are able to tell the firmware to interpret thrust as thrust (and not as climb rate) thus eliminating the reliance on internal altitude estimates.

**Comment by EceChaik** [comment]
Ooohh, very nice
